language: node_js
node_js:
  - '10'
branches:
  only:
    - main
cache:
  yarn: true
jobs:
  include:
    - stage: build-and-push
      name: Build and Push
      script: skip
      deploy:
        - provider: script
          on:
            branch: main
          script: .travis/build-and-push.sh
